spring:
  datasource:
    url: jdbc:h2:mem:ipmanagement
    platform: mysql
    username: auth
    password: auth
    driverClassName: org.h2.Driver
    liquibase:
      enabled: true
      default-schema: ipmanagement
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
application:
  ipaddress-regex: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"